import { autoSidebar } from "../src/util/autoSidebar";

export default {
    /**
     * front - start
     */
    "/html/": autoSidebar({ base: "html" }),
    "/css/": autoSidebar({ base: "css" }),
    "/javascript/": autoSidebar({ base: "javascript" }),
    "/git/": autoSidebar({ base: "git" }),
    "/less/": autoSidebar({ base: "less" }),
    "/webpack/": autoSidebar({ base: "webpack" }),
    "/vite/": autoSidebar({ base: "vite" }),
    "/typescript/": autoSidebar({ base: "typescript" }),
    "/react/": autoSidebar({ base: "react" }),
    "/umijs/": autoSidebar({ base: "umijs" }),
    "/antd/": autoSidebar({ base: "antd" }),
    "/react-native/": autoSidebar({ base: "react-native" }),
    "/network/": autoSidebar({ base: "network" }),
    "/nodejs/": autoSidebar({ base: "nodejs" }),
    "/sequelize/": autoSidebar({ base: "sequelize" }),
    "/mongodb/": autoSidebar({ base: "mongodb" }),
    '/redux/': autoSidebar({ base: "redux" }),
    "/echarts/": autoSidebar({ base: "echarts" }),
    "/axios/": autoSidebar({ base: "axios" }),
    "/jquery/": autoSidebar({ base: "jquery" }),
    "/bootstrap/": autoSidebar({ base: "bootstrap" }),
    "/moment/": autoSidebar({ base: "moment" }),
    "/dayjs/": autoSidebar({ base: "dayjs" }),
    "/lodash/": autoSidebar({ base: "lodash" }),
    "/ahooks/": autoSidebar({ base: "ahooks" }),
    "/usehook-ts/": autoSidebar({ base: "usehook-ts" }),
    "/md5/": autoSidebar({ base: "md5" }),
    "/classnames/": autoSidebar({ base: "classnames" }),
    "/swiper/": autoSidebar({ base: "swiper" }),
    "/validate/": autoSidebar({ base: "validate" }),
    "/validator/": autoSidebar({ base: "validator" }),
    // "/sequelize/": autoSidebar({ base: "sequelize" }),
    "/cheerio/": autoSidebar({ base: "cheerio" }),
    "/npm/": autoSidebar({ base: "npm" }),
    "/yarn/": autoSidebar({ base: "yarn" }),
    "/nvm/": autoSidebar({ base: "nvm" }),
    "/cnpm/": autoSidebar({ base: "cnpm" }),
    "/pnpm/": autoSidebar({ base: "pnpm" }),
    "/rust/": autoSidebar({ base: "rust" }),
    "/flutter/": autoSidebar({ base: "flutter" }),
    "/web-app/": autoSidebar({ base: "web-app" }),
    "/weixinapp/": autoSidebar({ base: "weixinapp" }),
    "/threejs/": autoSidebar({ base: "threejs" }),
    "/webgl/": autoSidebar({ base: "webgl" }),
    "/algorithm/": autoSidebar({ base: "algorithm" }),
    "/computer/": autoSidebar({ base: "computer" }),
    "/mysql/": autoSidebar({ base: "mysql" }),
    // "/mongodb/": autoSidebar({ base: "mongodb" }),
    // "/react-native/": autoSidebar({ base: "react-native" }),
    // "/sequelize/": autoSidebar({ base: "sequelize" }),
    // "/mongodb/": autoSidebar({ base: "mongodb" }),
    // "/react-native/": autoSidebar({ base: "react-native" }),
    // "/sequelize/": autoSidebar({ base: "sequelize" }),
};